# travis.yml
language: python
python: 3.8

stages:
  - pre-commit
  - master

jobs:
  include:
    - stage: master
      name: "Master commitlint"
      if: branch = master
      script:
        - commitlint-travis
      before_script:
        npm install --save-dev @commitlint/travis-cli
    - stage: pre-commit
      script: pre-commit run --all-files
      name: "Pre-commit run"
      before_script:
        - pip3 install pre-commit
    - stage: deploy docs
      install:
        - pip3 install mkdocs
        - pip3 install mkdocs-material
        - pip3 install mkdocs-git-revision-date-localized-plugin
      script: mkdocs build --verbose --clean --strict
      name: "Deploy MKDocs to GH-Pages"
      deploy:
        fqdn: docs.vivumlab.com
        provider: pages
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: site
        on:
          branch: master

cache:
  directories:
    - $HOME/.cache/pre-commit
