# travis.yml
language: node_js
node_js:
  - node

stages:
  - pre-commit
  - master

jobs:
  include:
    - stage: master
      name: "Master commitlint"
      if: branch = master
      script:
        - commitlint-travis
    - stage: pre-commit
      script: pre-commit run --from-ref origin/HEAD --to-ref HEAD
      name: "Pre-commit run"

before_script:
  - pip install pre-commit

cache:
  directories:
    - $HOME/.cache/pre-commit
