# travis.yml
language: ruby
os: linux
dist: xenial


stages:
  - pre-commit
  - name: master
    if: branch = master
  - deploy docs
  - name: release
    if: branch = master AND type = push AND fork = false
  - name: release-dry-run
    if: branch = dev AND type = push AND fork = false

jobs:
  include:
    - language: python
      python: 3.8
      stage: pre-commit
      name: "Pre-commit run"
      script: pre-commit run --all-files
      install:
        - pip3 install pre-commit
    - language: node_js
      node_js: node
      stage: master
      name: "Master commitlint"
      script:
        - commitlint-travis
    - language: python
      python: 3.8
      stage: deploy docs
      name: "Deploy MKDocs to GH-Pages"
      install:
        - pip3 install mkdocs
        - pip3 install mkdocs-material
        - pip3 install mkdocs-git-revision-date-localized-plugin
      script: mkdocs build --verbose --clean --strict
      deploy:
        fqdn: docs.vivumlab.com
        strategy: git
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN # Set in travis-ci.org dashboard
        local_dir: site
        on:
          branch: master
    - language: python
      sudo: required
      services:
        - docker
      stage: release
      name: "Release"
      before_install:
        - nvm install 12
        - npm install
      script:
        - npm run semantic-release
    - language: python
      sudo: required
      services:
        - docker
      stage: release-dry-run
      name: "Release Dry-Run"
      before_install:
        - nvm install 12
        - npm install
      script:
        - npm run semantic-release --dry-run

cache:
  directories:
    - $HOME/.cache/pre-commit
