# travis.yml
language: ruby
os: linux
dist: xenial


stages:
  - pre-commit
  - name: master
    if: branch = master
  - deploy docs
  - name: release
    if: branch = master

jobs:
  include:
    - language: python
      python: 3.8
      stage: pre-commit
      script: pre-commit run --all-files
      name: "Pre-commit run"
      install:
        - pip3 install pre-commit
    - language: node_js
      node_js: node
      stage: master
      name: "Master commitlint"
      script:
        - commitlint-travis
    - language: python
      python: 3.8
      stage: deploy docs
      install:
        - pip3 install mkdocs
        - pip3 install mkdocs-material
        - pip3 install mkdocs-git-revision-date-localized-plugin
      script: mkdocs build --verbose --clean --strict
      name: "Deploy MKDocs to GH-Pages"
      deploy:
        fqdn: docs.vivumlab.com
        strategy: git
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: site
        on:
          branch: master
    - language: python
      sudo: required
      services:
        - docker
      stage: release
      before_install:
        - nvm install 12
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script:
        - docker build . -t vlab
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - git config credential.helper "store --file=.git/credentials"
          - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
        script:
          # Use nvm to install and use the Node LTS version (nvm is installed on all Travis images)
          - npx standard-version
          - git push --follow-tags origin master
        on:
          branch: master

cache:
  directories:
    - $HOME/.cache/pre-commit
